### ISSUE TITLE
Setup error

### ISSUE THREAD

**Issue by DumbRadish** [SSASQueryAnalyzer/SSASQueryAnalyzer#2]
Following the install steps I receive a folder not found error 
![foldernotfounderror](https://user-images.githubusercontent.com/25682892/36380802-7b739c22-157b-11e8-8fda-5d54ccf00e99.PNG)

**Comment by albertospelta** [comment]
Hi @DumbRadish 

Which Windows OS version are you using?
The problem seems to be related to the version of PowerShell.

As I can see from the log and in particular from the environment information, you are using PowerShell version 2.0.
The installation script is not compatible with Powershell 2.0 and the minimum required version is 4.0.
Can you try upgrading to Powershell 4.0?

Unfortunately, a bug in the installation script does not correctly provide a check for this issue, I'll fix it ASAP.
Thanks!

**Comment by DumbRadish** [comment]
Yes upgrading to Powershell 4.0 worked. Thank you for your quick response.
